
package defaultnamespace.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.5
 * Wed Dec 08 16:22:28 WET 2021
 * Generated source version: 3.4.5
 */

@XmlRootElement(name = "listRooms", namespace = "http://server.soap.project/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listRooms", namespace = "http://server.soap.project/")

public class ListRooms {


}

