import project.soap.server.*;

import java.util.*;
import java.rmi.*;
import javax.jws.WebService;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane.SystemMenuBar;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

public class ClientSOAP {

    //Iniciar scanner para receber resposta do cliente
    private static Scanner receiveInput = new Scanner(System.in);

    public static void main(String args[]) {
        //List where we keep options
        ArrayList<Integer> optionList = new ArrayList<>(Arrays.asList(0, 1, 2, 3, 4, 5, 6));
        boolean userAuthenticated = false;
        String username = "";

        //Setup web service SOAP
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();

        //Use the URL defined in the soap address portion of the WSDL
        factory.setAddress("http://127.0.0.1:8090/HotelSOAP/services/WebServiceSoapPort");

        //Utilize the class which was generated by Apache CXF wsdl2java
        factory.setServiceClass(WebServiceSoap.class);

        //Client object with which we will be accessing methods
        Object hotelClient = factory.create();

        try {
            //Iniciar loop cliente, que só irá parar depois de cliente selecionar opção 0 de sair
            while (true) {
                //Mostrar menu ao cliente e receber resposta correta
                showMenu(username);
                int answer = -1;

                //Check if answer is in correct format and if it is part of the options
                while (true) {
                    System.out.print("Answer: ");
                    String userAnswer = receiveInput.nextLine();
                    boolean foundOption = false;

                    //Check if answer received is number
                    try {
                        answer = Integer.parseInt(userAnswer);

                        //Check if answer received is one of the options available
                        for (Integer option: optionList) {
                            if (answer == option) {
                                foundOption = true;
                            }
                        }
                        if (foundOption == true) {
                            break;
                        }

                        //Answer was not one of the options
                        System.out.println("Answer was not one of the options.");
                    } catch (NumberFormatException e) {
                        System.out.println("Answer was not one of the options.");
                    }
                }
                //Check if user wants to exit program
                if (answer == 0) {
                    break;
                }

                //Option of listing available rooms
                if (answer == 1) {
                    listRoomsHotel(hotelClient);
                }

                //Option of listing rooms currently reserved
                if (answer == 2) {
                    //Check if user is authenticated
                    if (userAuthenticated == false) {
                        System.out.println("You need to log in to choose that option.");
                        continue;
                    }

                    listRoomsReservedHotel(hotelClient, username);
                }

                //Option of reserving a room
                if (answer == 3) {
                    //Check if user is authenticated
                    if (userAuthenticated == false) {
                        System.out.println("You need to log in to choose that option.");
                        continue;
                    }

                    //Reserve room available in hotel
                    reserveRoomHotel(hotelClient, username);
                }

                //Option of canceling a reservation
                if (answer == 4) {
                    //Check if user is authenticated
                    if (userAuthenticated == false) {
                        System.out.println("You need to log in to choose that option.");
                        continue;
                    }

                    //List rooms user has reserved
                    listRoomsReservedHotel(hotelClient, username);

                    //Cancel reservation made from previous list
                    cancelReservationHotel(hotelClient, username);
                }

                //Option of logging in to account (get username and password)
                //Or logging out if already logged in
                if (answer == 5) {
                    //Logout of account as we are already in an account
                    if (!username.equals("")) {
                        System.out.println("Successfully logged out.");
                        userAuthenticated = false;
                        username = "";
                        continue;
                    }

                    //Login to account
                    String usernameReceived = loginClientHotel(hotelClient);

                    //Login worked out
                    if (usernameReceived != null) {
                        userAuthenticated = true;
                        username = usernameReceived;
                    }
                }

                //Option of registering account (setup username and password)
                if (answer == 6) {
                    String usernameReceived = registerClientHotel(hotelClient);

                    if (usernameReceived != null) {
                        userAuthenticated = true;
                        username = usernameReceived;
                    }
                }
            }
        } catch (Exception_Exception e) {
            System.out.println("Exception error -> " + e);
        }

        //Send message when user leaves client and server
        System.out.println("Thank you for choosing our hotel!");
    }

    //Show menu which will be used for the hotel
    public static void showMenu(String username) {
        System.out.println("------------Hotel Lisboa-------------");
        System.out.println("Bem vindo ao nosso Hotel!");
        System.out.println("1. Listar Quartos Disponiveis.");
        System.out.println("2. Listar Quartos Reservados.");
        System.out.println("3. Reservar um Quarto.");
        System.out.println("4. Cancelar uma Reserva.");
        if (username.equals("")) {
            System.out.println("5. Login.");
        } else { //Make sure user can logout of account if he so wishes
            System.out.println("5. Logout.");
        }
        System.out.println("6. Registar.");
        System.out.println("0. Sair.");
        System.out.println("-------------------------------------");
    }

    //Go to web service and list rooms of hotel
    public static void listRoomsHotel(Object hotelClient) throws Exception_Exception {
        System.out.println("Rooms available:");
        System.out.println(((WebServiceSoap)hotelClient).listRooms());
    }

    //Go to web service and list rooms that user has reserved
    public static void listRoomsReservedHotel(Object hotelClient, String username) throws Exception_Exception {
        System.out.println("Rooms currently reserved by " + username + ": ");
        System.out.println(((WebServiceSoap)hotelClient).listUserReservedRooms(username));
    }

    //Go to web service and reserve a room that is available on that date
    public static void reserveRoomHotel(Object hotelClient, String username) throws Exception_Exception {
        //Define format for reservations
        System.out.println("Reservations have a maximum amount of time of 1 month.");

        //First we get the date for the reservation
        String[] dates = getDateFromUser();
        if (dates == null) {
            return;
        }
        String initialDateChosen = dates[0];
        String finalDateChosen = dates[1];

        //Get rooms currently available from date given
        String roomsAvailable = ((WebServiceSoap)hotelClient).checkRoomsAtDate(initialDateChosen, finalDateChosen);
        System.out.println("Rooms available during that date: " + roomsAvailable);

        //Get the reservation from that list
        System.out.println("What room would you like to reserve?");
        String roomChosen = receiveInput.nextLine();

        //Check if the option chosen was in list
        String roomArray[] = roomsAvailable.split(" ");
        boolean foundRoom = false;
        for (String room: roomArray) {
            if (room.equals(roomChosen)) {
                foundRoom = true;
                break;
            }
        }

        //Check if room has enough capacity for client
        boolean capacityAnswer = checkRoomCapacity(roomChosen, foundRoom);
        if (capacityAnswer == false) {
            System.out.println("Room " + roomChosen + " did not have the desired capacity, please try a room from another floor.");
            return;
        }

        //Found available room chosen
        if (foundRoom == true) {
            //Send to server what room has to be reserved, when and by whom (will return false if error)
            boolean reservationAnswer =  ((WebServiceSoap)hotelClient).reserveRoom(roomChosen, initialDateChosen, finalDateChosen, username);
            if (reservationAnswer == true) {
                System.out.println("Room " + roomChosen + " has been reserved, thank you very much!");
            }
        } else {
            System.out.println("Room " + roomChosen + " was not found or is currently not available.");
        }
    }

    //Go to web service and remove the reservation of a room the user reserved
    public static void cancelReservationHotel(Object hotelClient, String username) throws Exception_Exception {
        //List rooms the client has reserved and cancel the reservation of one of them
        System.out.println("Hello user, what room would you like to cancel the reservation of?");
        String roomChosen = receiveInput.nextLine();

        //Get date reservation was made in
        String[] dates = getDateFromUser();
        if (dates == null) {
            return;
        }
        String initialDateChosen = dates[0];
        String finalDateChosen = dates[1];

        //Check if reservation was made and if we can remove it
        boolean removalAnswer = ((WebServiceSoap)hotelClient).removeReservation(roomChosen, initialDateChosen, finalDateChosen, username);
        if (removalAnswer == true) {
            System.out.println("Reservation for room " + roomChosen + " was canceled. Thank you very much!");
            return;
        }

        //Reservation was not found in file so cancelation wasnt made
        System.out.println("Reservation was not found, please try again!");
    }

    //Go to web service and login to an account
    public static String loginClientHotel(Object hotelClient) throws Exception_Exception {
        //Get account information
        System.out.print("Username: ");
        String usernameChosen = receiveInput.nextLine();
        System.out.print("Password: ");
        String passwordChosen = receiveInput.nextLine();

        //Check if account exists on server (receive int for multiple return answers)
        int loginAnswer = ((WebServiceSoap)hotelClient).loginAccount(usernameChosen, passwordChosen);
        if (loginAnswer == 0) {
            System.out.println("Successfully logged in to " + usernameChosen + ".");
            return usernameChosen;
        } else if (loginAnswer == -1) {
            System.out.println("Username was not found.");
        } else {
            System.out.println("Password for username was incorrect.");
        }

        //Account did not exist or password was wrong
        return null;
    }

    //Go to web service and register an account
    public static String registerClientHotel(Object hotelClient) throws Exception_Exception {
        //Define format required for username and password
        System.out.println("You can only use letters and numbers for your username and password.");

        //Setup account with username and password
        System.out.print("Setup Username: ");
        String usernameChosen = receiveInput.nextLine();
        System.out.print("Setup Password: ");
        String passwordChosen = receiveInput.nextLine();

        //Check if only letters and numbers were used
        boolean checkContent = checkUserFormat(usernameChosen, passwordChosen);
        if (!checkContent) {
            System.out.println("Error creating account, please try again.");
        }

        //Send account to server (will check if account and username are acceptable)
        boolean registerAnswer = ((WebServiceSoap)hotelClient).setupAccount(usernameChosen, passwordChosen);
        if (registerAnswer == true) {
            System.out.println("Account created successfully. You are now logged in to this account.");
            return usernameChosen;
        }

        System.out.println("Error creating account, please try again.");
        return null;
    }

    //Get initial and final dates from user
    public static String[] getDateFromUser() {
        //Ask user when reservation wants to be made
        System.out.println("Insert dates: (Format: DD/MM)");

        //Get dates for reservaton from user
        System.out.print("Initial Date: ");
        String initialDateChosen = receiveInput.nextLine();
        System.out.print("Final Date: ");
        String finalDateChosen = receiveInput.nextLine();

        //Check if dates are in correct format
        boolean checkFormat = checkDatesFormat(initialDateChosen, finalDateChosen);
        if (checkFormat == false) {
            System.out.println("Date was in the wrong format, please try again.");
            return null;
        }

        //Put dates into string and return to function
        String[] dates = new String[2];
        dates[0] = initialDateChosen;
        dates[1] = finalDateChosen;
        return dates;
    }

    //Check if answers are in required format
    public static boolean checkDatesFormat(String initialDate, String finalDate) {
        String splitInitialDate[] = initialDate.split("/");
        String splitFinalDate[] = finalDate.split("/");

        //Check length
        if (splitInitialDate.length != 2 || splitFinalDate.length != 2 ) {
            return false;
        }
        if (splitInitialDate[0].length() > 2 || splitInitialDate[1].length() > 2) {
            return false;
        }
        if (splitFinalDate[0].length() > 2 || splitFinalDate[1].length() > 2) {
            return false;
        }

        //Check if they are numbers and between possible days/month
        try {
            //Convert into int
            int initialDay = Integer.parseInt(splitInitialDate[0]);
            int initialMonth = Integer.parseInt(splitInitialDate[1]);
            int finalDay = Integer.parseInt(splitFinalDate[0]);
            int finalMonth = Integer.parseInt(splitFinalDate[1]);

            //Check if they are valid numbers (day and month)
            if ((initialDay < 1 || initialDay > 31) || (finalDay < 1 || finalDay > 31)) {
                return false;
            }
            if ((initialMonth < 1 || initialMonth > 12) || (finalMonth < 1 || finalMonth > 12)) {
                return false;
            }

            //Make sure month is okay for reservation (and check for new year exception)
            if (initialMonth == 12 && finalMonth == 1) {
                return true;
            } else {
                //Only allow reservations that are less, or equal, than 1 month (month)
                //Also only allows reserving months forward
                if (initialMonth - finalMonth == 0 || initialMonth - finalMonth == -1) {
                    //Make sure we are not reserving backwards in terms of days
                    if (initialMonth - finalMonth == 0) {
                        if (initialDay > finalDay) {
                            return false;
                        }
                    }
                } else {
                    return false;
                }
            }
        } catch (NumberFormatException e) {
            return false;
        }

        return true;
    }

    //Go through username and password and check if letters othen name chars and numbers were used
    public static boolean checkUserFormat(String username, String password) {
        //Go through username
        for (int pos = 0; pos < username.length() - 1; pos++) {
            char letter = username.charAt(pos);

            //Check if it is number or letter
            if (Character.isDigit(letter)) {
                //Check if it is actually number
                if (letter < 48 || letter > 57) {
                    return false;
                }
            } else {
                //Check if letter is upperscore or underscore
                if (Character.isUpperCase(letter)) {
                    //Check if it is actually letter
                    if (letter < 65 || letter > 90) {
                        return false;
                    }
                } else {
                    //Check if it is actually letter
                    if (letter < 97 || letter > 122) {
                        return false;
                    }
                }
            }
        }

        //Go through password
        for (int pos = 0; pos < password.length() - 1; pos++) {
            char letter = password.charAt(pos);

            //Check if it is number or letter
            if (Character.isDigit(letter)) {
                //Check if it is actually number
                if (letter < 48 || letter > 57) {
                    return false;
                }
            } else {
                //Check if letter is upperscore or underscore
                if (Character.isUpperCase(letter)) {
                    //Check if it is actually letter
                    if (letter < 65 || letter > 90) {
                        return false;
                    }
                } else {
                    //Check if it is actually letter
                    if (letter < 97 || letter > 122) {
                        return false;
                    }
                }
            }
        }

        return true;
    }

    //Give answer based on room chosen by user for capacity
    public static boolean checkRoomCapacity(String room, boolean foundRoom) {
        //Room was not found so let rest of function deal with it
        if (foundRoom == false) {
            return true;
        }

        //Check first letter of room
        char firstLetter = room.charAt(0);
        if (firstLetter == '1') {
            System.out.println("This room has the capacity of 2 people.");
        } else if (firstLetter == '2') {
            System.out.println("This room has the capacity of 3 people.");
        } else if (firstLetter == '3') {
            System.out.println("This room has the capacity of 6 people.");
        } else {
            return false;
        }

        //Ask user if they are ok with current room capacity
        System.out.println("Are you ok with this capacity? (Y/N)");
        String capacityAnswer = receiveInput.nextLine();
        if (capacityAnswer.charAt(0) == 'Y' || capacityAnswer.charAt(0) == 'y') {
            return true;
        }

        //User was not okay with room capacity
        return false;
    }
}