
package project.soap.server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-08T16:27:19.736Z
 * Generated source version: 3.4.5
 */

@WebFault(name = "Exception", targetNamespace = "http://server.soap.project/")
public class Exception_Exception extends java.lang.Exception {

    private project.soap.server.Exception faultInfo;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, project.soap.server.Exception exception) {
        super(message);
        this.faultInfo = exception;
    }

    public Exception_Exception(String message, project.soap.server.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = exception;
    }

    public project.soap.server.Exception getFaultInfo() {
        return this.faultInfo;
    }
}
