
package project.soap.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-08T16:27:19.496Z
 * Generated source version: 3.4.5
 *
 */
public final class WebServiceSoap_WebServiceSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.soap.project/", "WebServiceSoapService");

    private WebServiceSoap_WebServiceSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebServiceSoapService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WebServiceSoapService ss = new WebServiceSoapService(wsdlURL, SERVICE_NAME);
        WebServiceSoap port = ss.getWebServiceSoapPort();

        {
        System.out.println("Invoking setupAccount...");
        java.lang.String _setupAccount_arg0 = "_setupAccount_arg0-1557796052";
        java.lang.String _setupAccount_arg1 = "_setupAccount_arg1390995811";
        try {
            boolean _setupAccount__return = port.setupAccount(_setupAccount_arg0, _setupAccount_arg1);
            System.out.println("setupAccount.result=" + _setupAccount__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking loginAccount...");
        java.lang.String _loginAccount_arg0 = "_loginAccount_arg0748792105";
        java.lang.String _loginAccount_arg1 = "_loginAccount_arg1472293700";
        try {
            int _loginAccount__return = port.loginAccount(_loginAccount_arg0, _loginAccount_arg1);
            System.out.println("loginAccount.result=" + _loginAccount__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking listUserReservedRooms...");
        java.lang.String _listUserReservedRooms_arg0 = "_listUserReservedRooms_arg01270738474";
        try {
            java.lang.String _listUserReservedRooms__return = port.listUserReservedRooms(_listUserReservedRooms_arg0);
            System.out.println("listUserReservedRooms.result=" + _listUserReservedRooms__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking checkRoomsAtDate...");
        java.lang.String _checkRoomsAtDate_arg0 = "_checkRoomsAtDate_arg0217691503";
        java.lang.String _checkRoomsAtDate_arg1 = "_checkRoomsAtDate_arg1-80978351";
        try {
            java.lang.String _checkRoomsAtDate__return = port.checkRoomsAtDate(_checkRoomsAtDate_arg0, _checkRoomsAtDate_arg1);
            System.out.println("checkRoomsAtDate.result=" + _checkRoomsAtDate__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking reserveRoom...");
        java.lang.String _reserveRoom_arg0 = "_reserveRoom_arg0-1435398303";
        java.lang.String _reserveRoom_arg1 = "_reserveRoom_arg11097564340";
        java.lang.String _reserveRoom_arg2 = "_reserveRoom_arg2-1489083571";
        java.lang.String _reserveRoom_arg3 = "_reserveRoom_arg3-2057175080";
        try {
            boolean _reserveRoom__return = port.reserveRoom(_reserveRoom_arg0, _reserveRoom_arg1, _reserveRoom_arg2, _reserveRoom_arg3);
            System.out.println("reserveRoom.result=" + _reserveRoom__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking listRooms...");
        try {
            java.lang.String _listRooms__return = port.listRooms();
            System.out.println("listRooms.result=" + _listRooms__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking removeReservation...");
        java.lang.String _removeReservation_arg0 = "_removeReservation_arg0-1364117163";
        java.lang.String _removeReservation_arg1 = "_removeReservation_arg1-701692546";
        java.lang.String _removeReservation_arg2 = "_removeReservation_arg21474884831";
        java.lang.String _removeReservation_arg3 = "_removeReservation_arg3-2125094569";
        try {
            boolean _removeReservation__return = port.removeReservation(_removeReservation_arg0, _removeReservation_arg1, _removeReservation_arg2, _removeReservation_arg3);
            System.out.println("removeReservation.result=" + _removeReservation__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
