
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package project.soap.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-08T16:27:19.750Z
 * Generated source version: 3.4.5
 *
 */

@javax.jws.WebService(
                      serviceName = "WebServiceSoapService",
                      portName = "WebServiceSoapPort",
                      targetNamespace = "http://server.soap.project/",
                      wsdlLocation = "http://127.0.0.1:8090/HotelSOAP/services/WebServiceSoapPort?wsdl",
                      endpointInterface = "project.soap.server.WebServiceSoap")

public class WebServiceSoapPortImpl implements WebServiceSoap {

    private static final Logger LOG = Logger.getLogger(WebServiceSoapPortImpl.class.getName());

    /* (non-Javadoc)
     * @see project.soap.server.WebServiceSoap#setupAccount(java.lang.String arg0, java.lang.String arg1)*
     */
    public boolean setupAccount(java.lang.String arg0, java.lang.String arg1) throws Exception_Exception   {
        LOG.info("Executing operation setupAccount");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see project.soap.server.WebServiceSoap#loginAccount(java.lang.String arg0, java.lang.String arg1)*
     */
    public int loginAccount(java.lang.String arg0, java.lang.String arg1) throws Exception_Exception   {
        LOG.info("Executing operation loginAccount");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 1712789139;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see project.soap.server.WebServiceSoap#listUserReservedRooms(java.lang.String arg0)*
     */
    public java.lang.String listUserReservedRooms(java.lang.String arg0) throws Exception_Exception   {
        LOG.info("Executing operation listUserReservedRooms");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return589067878";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see project.soap.server.WebServiceSoap#checkRoomsAtDate(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String checkRoomsAtDate(java.lang.String arg0, java.lang.String arg1) throws Exception_Exception   {
        LOG.info("Executing operation checkRoomsAtDate");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1560784264";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see project.soap.server.WebServiceSoap#reserveRoom(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3)*
     */
    public boolean reserveRoom(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) throws Exception_Exception   {
        LOG.info("Executing operation reserveRoom");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see project.soap.server.WebServiceSoap#listRooms()*
     */
    public java.lang.String listRooms() throws Exception_Exception   {
        LOG.info("Executing operation listRooms");
        try {
            java.lang.String _return = "_return-1552204202";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see project.soap.server.WebServiceSoap#removeReservation(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3)*
     */
    public boolean removeReservation(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) throws Exception_Exception   {
        LOG.info("Executing operation removeReservation");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
