package project.soap.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-08T16:27:19.811Z
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "WebServiceSoapService",
                  wsdlLocation = "http://127.0.0.1:8090/HotelSOAP/services/WebServiceSoapPort?wsdl",
                  targetNamespace = "http://server.soap.project/")
public class WebServiceSoapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.soap.project/", "WebServiceSoapService");
    public final static QName WebServiceSoapPort = new QName("http://server.soap.project/", "WebServiceSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8090/HotelSOAP/services/WebServiceSoapPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServiceSoapService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8090/HotelSOAP/services/WebServiceSoapPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServiceSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServiceSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceSoapService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WebServiceSoapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebServiceSoapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebServiceSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WebServiceSoap
     */
    @WebEndpoint(name = "WebServiceSoapPort")
    public WebServiceSoap getWebServiceSoapPort() {
        return super.getPort(WebServiceSoapPort, WebServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceSoap
     */
    @WebEndpoint(name = "WebServiceSoapPort")
    public WebServiceSoap getWebServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(WebServiceSoapPort, WebServiceSoap.class, features);
    }

}
