package project.soap.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-08T16:27:19.789Z
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://server.soap.project/", name = "WebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceSoap {

    @WebMethod
    @RequestWrapper(localName = "setupAccount", targetNamespace = "http://server.soap.project/", className = "project.soap.server.SetupAccount")
    @ResponseWrapper(localName = "setupAccountResponse", targetNamespace = "http://server.soap.project/", className = "project.soap.server.SetupAccountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean setupAccount(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "loginAccount", targetNamespace = "http://server.soap.project/", className = "project.soap.server.LoginAccount")
    @ResponseWrapper(localName = "loginAccountResponse", targetNamespace = "http://server.soap.project/", className = "project.soap.server.LoginAccountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int loginAccount(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "listUserReservedRooms", targetNamespace = "http://server.soap.project/", className = "project.soap.server.ListUserReservedRooms")
    @ResponseWrapper(localName = "listUserReservedRoomsResponse", targetNamespace = "http://server.soap.project/", className = "project.soap.server.ListUserReservedRoomsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String listUserReservedRooms(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "checkRoomsAtDate", targetNamespace = "http://server.soap.project/", className = "project.soap.server.CheckRoomsAtDate")
    @ResponseWrapper(localName = "checkRoomsAtDateResponse", targetNamespace = "http://server.soap.project/", className = "project.soap.server.CheckRoomsAtDateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkRoomsAtDate(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "reserveRoom", targetNamespace = "http://server.soap.project/", className = "project.soap.server.ReserveRoom")
    @ResponseWrapper(localName = "reserveRoomResponse", targetNamespace = "http://server.soap.project/", className = "project.soap.server.ReserveRoomResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean reserveRoom(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "listRooms", targetNamespace = "http://server.soap.project/", className = "project.soap.server.ListRooms")
    @ResponseWrapper(localName = "listRoomsResponse", targetNamespace = "http://server.soap.project/", className = "project.soap.server.ListRoomsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String listRooms()
 throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "removeReservation", targetNamespace = "http://server.soap.project/", className = "project.soap.server.RemoveReservation")
    @ResponseWrapper(localName = "removeReservationResponse", targetNamespace = "http://server.soap.project/", className = "project.soap.server.RemoveReservationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeReservation(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    ) throws Exception_Exception;
}
